---
# tasks file for php
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - php7.2-mysql
    - mariadb-client
    - php7.2
    - libapache2-mod-php7.2
    - python-mysqldb
    - zip
    - libapache2-mod-php7.2
    - php7.2-common
    - php7.2-mysql
    - php7.2-gmp
    - php7.2-curl
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-xmlrpc
    - php7.2-gd
    - php7.2-bcmath
    - php7.2-imap
    - php7.2-xml
    - php7.2-cli
    - php7.2-zip
    - unzip
    - php-xml-parser
