---
# handlers file for php
- name: restart apache
  service: name=apache2 state=restarted
  become: yes


- name: Enable service Apache2, and not touch the state
  service:
    name: apache2
    enabled: yes

